### PR TITLE
chore: add backstory for graduation ebee

### PR DESCRIPTION
**Pull request by hacktivist123**
closes: #77

### CODE REVIEW

**Review by qmonnet — CHANGES_REQUESTED** [review]
Looks good. Two comments:

- I edited your image (but not your PR) to make it consistent with the other pictures: I cropped to content and scale down to 577x577 pixels. Here is my version:
  graduation-bee

- I see you made this eBee male. Just as a note, we tried initially to have the same number of male and female eBees in the list (although some don't use any gender in the description). I haven't counted recently to see where we're at now, but this is something to keep in mind for future contributions.

Also, a minor observation below.

**Comment by hacktivist123** [comment]
Thanks for your review @qmonnet will update the PR with your suggestions! 

Good catch on the gender of the bee, will keep what you have said in mind

**Comment by hacktivist123** [comment]
updated the PR @qmonnet

**Review by qmonnet — APPROVED** [review]
Thanks! 30 eBees already :exploding_head:

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
