### PR TITLE
Add Caribbean eBee

### PR DESCRIPTION
**Pull request by qmonnet**
image

Number 21, to be merged after Bounty Hunter eBee?

### CODE REVIEW

**Comment by xmulligan** [comment]
Do you want to want to switch to the [Mexican Beer Sour](https://isovalent.slack.com/archives/C3ZHQRRKM/p1681525776607719?thread_ts=1681525665.001519&cid=C3ZHQRRKM)? Otherwise looks good to me 🏖️

**Review by xmulligan — APPROVED** [review]

**Comment by xmulligan** [comment]
No, so let's leave it out for now. Happy to merge after # 20 is added

**Comment by xmulligan** [comment]
If you can resolve the conflicts, I'm happy to merge as # 21

**Comment by qmonnet** [comment]
@xmulligan Thanks! I just rebased, we should be good to go.

**Comment by qmonnet** [comment]
Silly me - I can just merge it myself.

**Pull request merged**
